name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build & Test
        uses: ashutoshvarma/action-cmake-build@master
        with:
            build-dir: ${{ runner.workspace }}/build
            cc: gcc
            cxx: g++
            build-type: Release
            run-test: false
            ctest-options: -R mytest
            install-build: false
            parallel: 14
