name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: creating build directory
      run: mkdir build && cd build
    - name: running cmake
      run: cmake ..
    - name: make
      run: make
    - name: run app
      run: ./CPMNuker
